import {
  DashboardWallet,
  DashboardBudget,
  DashboardCashLog,
  DashboardCategory,
} from '@/features/dashboard/types/dashboard';

// ─── Categories ───
export const mockCategories: DashboardCategory[] = [
  { id: 1, name: 'Salary', type: 'income', parentId: null },
  { id: 2, name: 'Freelance', type: 'income', parentId: null },
  { id: 3, name: 'Investment Return', type: 'income', parentId: null },
  { id: 10, name: 'Food & Drink', type: 'outcome', parentId: null },
  { id: 11, name: 'Groceries', type: 'outcome', parentId: 10 },
  { id: 12, name: 'Eating Out', type: 'outcome', parentId: 10 },
  { id: 20, name: 'Transport', type: 'outcome', parentId: null },
  { id: 21, name: 'Fuel', type: 'outcome', parentId: 20 },
  { id: 22, name: 'Grab/Gojek', type: 'outcome', parentId: 20 },
  { id: 30, name: 'Housing', type: 'outcome', parentId: null },
  { id: 31, name: 'Rent', type: 'outcome', parentId: 30 },
  { id: 32, name: 'Utilities', type: 'outcome', parentId: 30 },
  { id: 40, name: 'Entertainment', type: 'outcome', parentId: null },
  { id: 41, name: 'Movies', type: 'outcome', parentId: 40 },
  { id: 42, name: 'Streaming', type: 'outcome', parentId: 40 },
  { id: 50, name: 'Shopping', type: 'outcome', parentId: null },
  { id: 51, name: 'Fashion', type: 'outcome', parentId: 50 },
  { id: 52, name: 'Gadgets', type: 'outcome', parentId: 50 },
  { id: 60, name: 'Health', type: 'outcome', parentId: null },
  { id: 70, name: 'Education', type: 'outcome', parentId: null },
  { id: 80, name: 'Savings', type: 'outcome', parentId: null },
  { id: 81, name: 'Emergency Savings', type: 'outcome', parentId: 80 },
  { id: 82, name: 'Investment Savings', type: 'outcome', parentId: 80 },
  { id: 90, name: 'Transfer In', type: 'income', parentId: null },
  { id: 91, name: 'Transfer Out', type: 'outcome', parentId: null },
];

// ─── Wallets ───
export const mockWallets: DashboardWallet[] = [
  { id: 1, name: 'BCA', balance: 15_200_000, excludeFromTotal: false },
  { id: 2, name: 'Mandiri', balance: 8_750_000, excludeFromTotal: false },
  { id: 3, name: 'Cash', balance: 1_350_000, excludeFromTotal: false },
  { id: 4, name: 'GoPay', balance: 520_000, excludeFromTotal: false },
  {
    id: 5,
    name: 'Emergency Fund',
    balance: 25_000_000,
    excludeFromTotal: true,
  },
];

// ─── Monthly Budgets (6 months: Oct 2025 – Mar 2026) ───
export const mockBudgets: DashboardBudget[] = [
  // Oct 2025
  {
    id: 1,
    name: 'Salary',
    amount: 12_000_000,
    month: '2025-10',
    category: 'Salary',
    type: 'income',
  },
  {
    id: 2,
    name: 'Freelance',
    amount: 3_000_000,
    month: '2025-10',
    category: 'Freelance',
    type: 'income',
  },
  {
    id: 3,
    name: 'Rent',
    amount: 3_500_000,
    month: '2025-10',
    category: 'Rent',
    type: 'outcome',
  },
  {
    id: 4,
    name: 'Groceries',
    amount: 2_000_000,
    month: '2025-10',
    category: 'Groceries',
    type: 'outcome',
  },
  {
    id: 5,
    name: 'Transport',
    amount: 800_000,
    month: '2025-10',
    category: 'Transport',
    type: 'outcome',
  },
  {
    id: 6,
    name: 'Entertainment',
    amount: 500_000,
    month: '2025-10',
    category: 'Entertainment',
    type: 'outcome',
  },
  {
    id: 7,
    name: 'Savings',
    amount: 3_000_000,
    month: '2025-10',
    category: 'Savings',
    type: 'outcome',
  },
  {
    id: 8,
    name: 'Shopping',
    amount: 1_200_000,
    month: '2025-10',
    category: 'Shopping',
    type: 'outcome',
  },
  {
    id: 9,
    name: 'Health',
    amount: 500_000,
    month: '2025-10',
    category: 'Health',
    type: 'outcome',
  },

  // Nov 2025
  {
    id: 10,
    name: 'Salary',
    amount: 12_000_000,
    month: '2025-11',
    category: 'Salary',
    type: 'income',
  },
  {
    id: 11,
    name: 'Freelance',
    amount: 2_500_000,
    month: '2025-11',
    category: 'Freelance',
    type: 'income',
  },
  {
    id: 12,
    name: 'Rent',
    amount: 3_500_000,
    month: '2025-11',
    category: 'Rent',
    type: 'outcome',
  },
  {
    id: 13,
    name: 'Groceries',
    amount: 2_200_000,
    month: '2025-11',
    category: 'Groceries',
    type: 'outcome',
  },
  {
    id: 14,
    name: 'Transport',
    amount: 750_000,
    month: '2025-11',
    category: 'Transport',
    type: 'outcome',
  },
  {
    id: 15,
    name: 'Entertainment',
    amount: 600_000,
    month: '2025-11',
    category: 'Entertainment',
    type: 'outcome',
  },
  {
    id: 16,
    name: 'Savings',
    amount: 3_000_000,
    month: '2025-11',
    category: 'Savings',
    type: 'outcome',
  },
  {
    id: 17,
    name: 'Education',
    amount: 1_000_000,
    month: '2025-11',
    category: 'Education',
    type: 'outcome',
  },

  // Dec 2025
  {
    id: 18,
    name: 'Salary',
    amount: 12_000_000,
    month: '2025-12',
    category: 'Salary',
    type: 'income',
  },
  {
    id: 19,
    name: 'Freelance',
    amount: 4_000_000,
    month: '2025-12',
    category: 'Freelance',
    type: 'income',
  },
  {
    id: 20,
    name: 'Bonus',
    amount: 6_000_000,
    month: '2025-12',
    category: 'Salary',
    type: 'income',
  },
  {
    id: 21,
    name: 'Rent',
    amount: 3_500_000,
    month: '2025-12',
    category: 'Rent',
    type: 'outcome',
  },
  {
    id: 22,
    name: 'Groceries',
    amount: 2_500_000,
    month: '2025-12',
    category: 'Groceries',
    type: 'outcome',
  },
  {
    id: 23,
    name: 'Transport',
    amount: 900_000,
    month: '2025-12',
    category: 'Transport',
    type: 'outcome',
  },
  {
    id: 24,
    name: 'Entertainment',
    amount: 1_500_000,
    month: '2025-12',
    category: 'Entertainment',
    type: 'outcome',
  },
  {
    id: 25,
    name: 'Savings',
    amount: 5_000_000,
    month: '2025-12',
    category: 'Savings',
    type: 'outcome',
  },
  {
    id: 26,
    name: 'Shopping',
    amount: 3_000_000,
    month: '2025-12',
    category: 'Shopping',
    type: 'outcome',
  },

  // Jan 2026
  {
    id: 27,
    name: 'Salary',
    amount: 13_000_000,
    month: '2026-01',
    category: 'Salary',
    type: 'income',
  },
  {
    id: 28,
    name: 'Freelance',
    amount: 2_000_000,
    month: '2026-01',
    category: 'Freelance',
    type: 'income',
  },
  {
    id: 29,
    name: 'Rent',
    amount: 3_500_000,
    month: '2026-01',
    category: 'Rent',
    type: 'outcome',
  },
  {
    id: 30,
    name: 'Groceries',
    amount: 2_000_000,
    month: '2026-01',
    category: 'Groceries',
    type: 'outcome',
  },
  {
    id: 31,
    name: 'Transport',
    amount: 800_000,
    month: '2026-01',
    category: 'Transport',
    type: 'outcome',
  },
  {
    id: 32,
    name: 'Entertainment',
    amount: 400_000,
    month: '2026-01',
    category: 'Entertainment',
    type: 'outcome',
  },
  {
    id: 33,
    name: 'Savings',
    amount: 3_000_000,
    month: '2026-01',
    category: 'Savings',
    type: 'outcome',
  },
  {
    id: 34,
    name: 'Health',
    amount: 800_000,
    month: '2026-01',
    category: 'Health',
    type: 'outcome',
  },

  // Feb 2026
  {
    id: 35,
    name: 'Salary',
    amount: 13_000_000,
    month: '2026-02',
    category: 'Salary',
    type: 'income',
  },
  {
    id: 36,
    name: 'Freelance',
    amount: 3_500_000,
    month: '2026-02',
    category: 'Freelance',
    type: 'income',
  },
  {
    id: 37,
    name: 'Rent',
    amount: 3_500_000,
    month: '2026-02',
    category: 'Rent',
    type: 'outcome',
  },
  {
    id: 38,
    name: 'Groceries',
    amount: 2_100_000,
    month: '2026-02',
    category: 'Groceries',
    type: 'outcome',
  },
  {
    id: 39,
    name: 'Transport',
    amount: 850_000,
    month: '2026-02',
    category: 'Transport',
    type: 'outcome',
  },
  {
    id: 40,
    name: 'Entertainment',
    amount: 700_000,
    month: '2026-02',
    category: 'Entertainment',
    type: 'outcome',
  },
  {
    id: 41,
    name: 'Savings',
    amount: 4_000_000,
    month: '2026-02',
    category: 'Savings',
    type: 'outcome',
  },
  {
    id: 42,
    name: 'Education',
    amount: 1_200_000,
    month: '2026-02',
    category: 'Education',
    type: 'outcome',
  },

  // Mar 2026 (current month)
  {
    id: 43,
    name: 'Salary',
    amount: 13_000_000,
    month: '2026-03',
    category: 'Salary',
    type: 'income',
  },
  {
    id: 44,
    name: 'Freelance',
    amount: 3_000_000,
    month: '2026-03',
    category: 'Freelance',
    type: 'income',
  },
  {
    id: 45,
    name: 'Investment Return',
    amount: 500_000,
    month: '2026-03',
    category: 'Investment Return',
    type: 'income',
  },
  {
    id: 46,
    name: 'Rent',
    amount: 3_500_000,
    month: '2026-03',
    category: 'Rent',
    type: 'outcome',
  },
  {
    id: 47,
    name: 'Groceries',
    amount: 2_200_000,
    month: '2026-03',
    category: 'Groceries',
    type: 'outcome',
  },
  {
    id: 48,
    name: 'Transport',
    amount: 900_000,
    month: '2026-03',
    category: 'Transport',
    type: 'outcome',
  },
  {
    id: 49,
    name: 'Entertainment',
    amount: 600_000,
    month: '2026-03',
    category: 'Entertainment',
    type: 'outcome',
  },
  {
    id: 50,
    name: 'Savings',
    amount: 3_500_000,
    month: '2026-03',
    category: 'Savings',
    type: 'outcome',
  },
  {
    id: 51,
    name: 'Shopping',
    amount: 1_000_000,
    month: '2026-03',
    category: 'Shopping',
    type: 'outcome',
  },
  {
    id: 52,
    name: 'Health',
    amount: 600_000,
    month: '2026-03',
    category: 'Health',
    type: 'outcome',
  },
  {
    id: 53,
    name: 'Education',
    amount: 800_000,
    month: '2026-03',
    category: 'Education',
    type: 'outcome',
  },
];

// ─── Cash Logs (current month: Mar 2026 – partially realized) ───
export const mockCashLogs: DashboardCashLog[] = [
  // Mar 1
  {
    id: 101,
    date: '2026-03-01',
    description: 'Monthly Salary',
    amount: 13_000_000,
    walletName: 'BCA',
    categoryId: 1,
    excludeFromReport: false,
    category: { id: 1, name: 'Salary', type: 'income', parentId: null },
  },
  {
    id: 102,
    date: '2026-03-01',
    description: 'Rent Payment',
    amount: 3_500_000,
    walletName: 'BCA',
    categoryId: 31,
    excludeFromReport: false,
    category: { id: 31, name: 'Rent', type: 'outcome', parentId: 30 },
  },
  // Mar 2
  {
    id: 103,
    date: '2026-03-02',
    description: 'Groceries at Superindo',
    amount: 450_000,
    walletName: 'Cash',
    categoryId: 11,
    excludeFromReport: false,
    category: { id: 11, name: 'Groceries', type: 'outcome', parentId: 10 },
  },
  {
    id: 104,
    date: '2026-03-02',
    description: 'Grab to office',
    amount: 35_000,
    walletName: 'GoPay',
    categoryId: 22,
    excludeFromReport: false,
    category: { id: 22, name: 'Grab/Gojek', type: 'outcome', parentId: 20 },
  },
  // Mar 3
  {
    id: 105,
    date: '2026-03-03',
    description: 'Freelance project payment',
    amount: 3_000_000,
    walletName: 'Mandiri',
    categoryId: 2,
    excludeFromReport: false,
    category: { id: 2, name: 'Freelance', type: 'income', parentId: null },
  },
  {
    id: 106,
    date: '2026-03-03',
    description: 'Lunch with team',
    amount: 120_000,
    walletName: 'GoPay',
    categoryId: 12,
    excludeFromReport: false,
    category: { id: 12, name: 'Eating Out', type: 'outcome', parentId: 10 },
  },
  // Mar 5
  {
    id: 107,
    date: '2026-03-05',
    description: 'Fuel',
    amount: 250_000,
    walletName: 'BCA',
    categoryId: 21,
    excludeFromReport: false,
    category: { id: 21, name: 'Fuel', type: 'outcome', parentId: 20 },
  },
  {
    id: 108,
    date: '2026-03-05',
    description: 'Netflix subscription',
    amount: 186_000,
    walletName: 'BCA',
    categoryId: 42,
    excludeFromReport: false,
    category: {
      id: 42,
      name: 'Streaming',
      type: 'outcome',
      parentId: 40,
    },
  },
  // Mar 7
  {
    id: 109,
    date: '2026-03-07',
    description: 'Weekly groceries',
    amount: 380_000,
    walletName: 'Cash',
    categoryId: 11,
    excludeFromReport: false,
    category: { id: 11, name: 'Groceries', type: 'outcome', parentId: 10 },
  },
  {
    id: 110,
    date: '2026-03-07',
    description: 'Electricity bill',
    amount: 450_000,
    walletName: 'BCA',
    categoryId: 32,
    excludeFromReport: false,
    category: { id: 32, name: 'Utilities', type: 'outcome', parentId: 30 },
  },
  {
    id: 111,
    date: '2026-03-07',
    description: 'Internet bill',
    amount: 350_000,
    walletName: 'BCA',
    categoryId: 32,
    excludeFromReport: false,
    category: { id: 32, name: 'Utilities', type: 'outcome', parentId: 30 },
  },
  // Mar 8
  {
    id: 112,
    date: '2026-03-08',
    description: 'Online course - Udemy',
    amount: 200_000,
    walletName: 'BCA',
    categoryId: 70,
    excludeFromReport: false,
    category: { id: 70, name: 'Education', type: 'outcome', parentId: null },
  },
  // Mar 10
  {
    id: 113,
    date: '2026-03-10',
    description: 'Pharmacy',
    amount: 150_000,
    walletName: 'Cash',
    categoryId: 60,
    excludeFromReport: false,
    category: { id: 60, name: 'Health', type: 'outcome', parentId: null },
  },
  {
    id: 114,
    date: '2026-03-10',
    description: 'Grab rides',
    amount: 85_000,
    walletName: 'GoPay',
    categoryId: 22,
    excludeFromReport: false,
    category: { id: 22, name: 'Grab/Gojek', type: 'outcome', parentId: 20 },
  },
  // Mar 12
  {
    id: 115,
    date: '2026-03-12',
    description: 'Groceries at Alfamart',
    amount: 180_000,
    walletName: 'Cash',
    categoryId: 11,
    excludeFromReport: false,
    category: { id: 11, name: 'Groceries', type: 'outcome', parentId: 10 },
  },
  {
    id: 116,
    date: '2026-03-12',
    description: 'Coffee with client',
    amount: 95_000,
    walletName: 'GoPay',
    categoryId: 12,
    excludeFromReport: false,
    category: { id: 12, name: 'Eating Out', type: 'outcome', parentId: 10 },
  },
  // Mar 14
  {
    id: 117,
    date: '2026-03-14',
    description: 'New shoes',
    amount: 650_000,
    walletName: 'BCA',
    categoryId: 51,
    excludeFromReport: false,
    category: { id: 51, name: 'Fashion', type: 'outcome', parentId: 50 },
  },
  {
    id: 118,
    date: '2026-03-14',
    description: 'Dinner out',
    amount: 250_000,
    walletName: 'Cash',
    categoryId: 12,
    excludeFromReport: false,
    category: { id: 12, name: 'Eating Out', type: 'outcome', parentId: 10 },
  },
  // Mar 15
  {
    id: 119,
    date: '2026-03-15',
    description: 'Investment return',
    amount: 500_000,
    walletName: 'Mandiri',
    categoryId: 3,
    excludeFromReport: false,
    category: {
      id: 3,
      name: 'Investment Return',
      type: 'income',
      parentId: null,
    },
  },
  {
    id: 120,
    date: '2026-03-15',
    description: 'Transfer savings',
    amount: 3_500_000,
    walletName: 'BCA',
    categoryId: 81,
    excludeFromReport: false,
    category: {
      id: 81,
      name: 'Emergency Savings',
      type: 'outcome',
      parentId: 80,
    },
  },
  // Mar 16
  {
    id: 121,
    date: '2026-03-16',
    description: 'Groceries weekend',
    amount: 320_000,
    walletName: 'Cash',
    categoryId: 11,
    excludeFromReport: false,
    category: { id: 11, name: 'Groceries', type: 'outcome', parentId: 10 },
  },
  {
    id: 122,
    date: '2026-03-16',
    description: 'Movie tickets',
    amount: 120_000,
    walletName: 'GoPay',
    categoryId: 41,
    excludeFromReport: false,
    category: {
      id: 41,
      name: 'Movies',
      type: 'outcome',
      parentId: 40,
    },
  },

  // ─── Historical logs for trend (summarized per month) ───
  // Feb 2026
  {
    id: 201,
    date: '2026-02-01',
    description: 'Salary Feb',
    amount: 13_000_000,
    walletName: 'BCA',
    categoryId: 1,
    excludeFromReport: false,
    category: { id: 1, name: 'Salary', type: 'income', parentId: null },
  },
  {
    id: 202,
    date: '2026-02-05',
    description: 'Freelance Feb',
    amount: 3_500_000,
    walletName: 'Mandiri',
    categoryId: 2,
    excludeFromReport: false,
    category: { id: 2, name: 'Freelance', type: 'income', parentId: null },
  },
  {
    id: 203,
    date: '2026-02-01',
    description: 'Rent Feb',
    amount: 3_500_000,
    walletName: 'BCA',
    categoryId: 31,
    excludeFromReport: false,
    category: { id: 31, name: 'Rent', type: 'outcome', parentId: 30 },
  },
  {
    id: 204,
    date: '2026-02-10',
    description: 'Groceries Feb',
    amount: 1_800_000,
    walletName: 'Cash',
    categoryId: 11,
    excludeFromReport: false,
    category: { id: 11, name: 'Groceries', type: 'outcome', parentId: 10 },
  },
  {
    id: 205,
    date: '2026-02-12',
    description: 'Transport Feb',
    amount: 720_000,
    walletName: 'GoPay',
    categoryId: 20,
    excludeFromReport: false,
    category: { id: 20, name: 'Transport', type: 'outcome', parentId: null },
  },
  {
    id: 206,
    date: '2026-02-15',
    description: 'Savings Feb',
    amount: 4_000_000,
    walletName: 'BCA',
    categoryId: 82,
    excludeFromReport: false,
    category: {
      id: 82,
      name: 'Investment Savings',
      type: 'outcome',
      parentId: 80,
    },
  },
  {
    id: 207,
    date: '2026-02-18',
    description: 'Entertainment Feb',
    amount: 550_000,
    walletName: 'GoPay',
    categoryId: 42,
    excludeFromReport: false,
    category: {
      id: 42,
      name: 'Streaming',
      type: 'outcome',
      parentId: 40,
    },
  },
  {
    id: 208,
    date: '2026-02-20',
    description: 'Education Feb',
    amount: 1_200_000,
    walletName: 'BCA',
    categoryId: 70,
    excludeFromReport: false,
    category: { id: 70, name: 'Education', type: 'outcome', parentId: null },
  },

  // Jan 2026
  {
    id: 301,
    date: '2026-01-01',
    description: 'Salary Jan',
    amount: 13_000_000,
    walletName: 'BCA',
    categoryId: 1,
    excludeFromReport: false,
    category: { id: 1, name: 'Salary', type: 'income', parentId: null },
  },
  {
    id: 302,
    date: '2026-01-05',
    description: 'Freelance Jan',
    amount: 2_000_000,
    walletName: 'Mandiri',
    categoryId: 2,
    excludeFromReport: false,
    category: { id: 2, name: 'Freelance', type: 'income', parentId: null },
  },
  {
    id: 303,
    date: '2026-01-01',
    description: 'Rent Jan',
    amount: 3_500_000,
    walletName: 'BCA',
    categoryId: 31,
    excludeFromReport: false,
    category: { id: 31, name: 'Rent', type: 'outcome', parentId: 30 },
  },
  {
    id: 304,
    date: '2026-01-10',
    description: 'Groceries Jan',
    amount: 1_900_000,
    walletName: 'Cash',
    categoryId: 11,
    excludeFromReport: false,
    category: { id: 11, name: 'Groceries', type: 'outcome', parentId: 10 },
  },
  {
    id: 305,
    date: '2026-01-15',
    description: 'Transport Jan',
    amount: 680_000,
    walletName: 'GoPay',
    categoryId: 20,
    excludeFromReport: false,
    category: { id: 20, name: 'Transport', type: 'outcome', parentId: null },
  },
  {
    id: 306,
    date: '2026-01-15',
    description: 'Savings Jan',
    amount: 3_000_000,
    walletName: 'BCA',
    categoryId: 81,
    excludeFromReport: false,
    category: {
      id: 81,
      name: 'Emergency Savings',
      type: 'outcome',
      parentId: 80,
    },
  },
  {
    id: 307,
    date: '2026-01-20',
    description: 'Health Jan',
    amount: 800_000,
    walletName: 'Cash',
    categoryId: 60,
    excludeFromReport: false,
    category: { id: 60, name: 'Health', type: 'outcome', parentId: null },
  },

  // Dec 2025
  {
    id: 401,
    date: '2025-12-01',
    description: 'Salary Dec',
    amount: 12_000_000,
    walletName: 'BCA',
    categoryId: 1,
    excludeFromReport: false,
    category: { id: 1, name: 'Salary', type: 'income', parentId: null },
  },
  {
    id: 402,
    date: '2025-12-05',
    description: 'Freelance Dec',
    amount: 4_000_000,
    walletName: 'Mandiri',
    categoryId: 2,
    excludeFromReport: false,
    category: { id: 2, name: 'Freelance', type: 'income', parentId: null },
  },
  {
    id: 403,
    date: '2025-12-10',
    description: 'Bonus Dec',
    amount: 6_000_000,
    walletName: 'BCA',
    categoryId: 1,
    excludeFromReport: false,
    category: { id: 1, name: 'Salary', type: 'income', parentId: null },
  },
  {
    id: 404,
    date: '2025-12-01',
    description: 'Rent Dec',
    amount: 3_500_000,
    walletName: 'BCA',
    categoryId: 31,
    excludeFromReport: false,
    category: { id: 31, name: 'Rent', type: 'outcome', parentId: 30 },
  },
  {
    id: 405,
    date: '2025-12-15',
    description: 'Groceries Dec',
    amount: 2_300_000,
    walletName: 'Cash',
    categoryId: 11,
    excludeFromReport: false,
    category: { id: 11, name: 'Groceries', type: 'outcome', parentId: 10 },
  },
  {
    id: 406,
    date: '2025-12-20',
    description: 'Shopping Dec',
    amount: 2_800_000,
    walletName: 'BCA',
    categoryId: 52,
    excludeFromReport: false,
    category: { id: 52, name: 'Gadgets', type: 'outcome', parentId: 50 },
  },
  {
    id: 407,
    date: '2025-12-22',
    description: 'Entertainment Dec',
    amount: 1_400_000,
    walletName: 'GoPay',
    categoryId: 41,
    excludeFromReport: false,
    category: {
      id: 41,
      name: 'Movies',
      type: 'outcome',
      parentId: 40,
    },
  },
  {
    id: 408,
    date: '2025-12-25',
    description: 'Savings Dec',
    amount: 5_000_000,
    walletName: 'BCA',
    categoryId: 82,
    excludeFromReport: false,
    category: {
      id: 82,
      name: 'Investment Savings',
      type: 'outcome',
      parentId: 80,
    },
  },

  // Nov 2025
  {
    id: 501,
    date: '2025-11-01',
    description: 'Salary Nov',
    amount: 12_000_000,
    walletName: 'BCA',
    categoryId: 1,
    excludeFromReport: false,
    category: { id: 1, name: 'Salary', type: 'income', parentId: null },
  },
  {
    id: 502,
    date: '2025-11-05',
    description: 'Freelance Nov',
    amount: 2_500_000,
    walletName: 'Mandiri',
    categoryId: 2,
    excludeFromReport: false,
    category: { id: 2, name: 'Freelance', type: 'income', parentId: null },
  },
  {
    id: 503,
    date: '2025-11-01',
    description: 'Rent Nov',
    amount: 3_500_000,
    walletName: 'BCA',
    categoryId: 31,
    excludeFromReport: false,
    category: { id: 31, name: 'Rent', type: 'outcome', parentId: 30 },
  },
  {
    id: 504,
    date: '2025-11-10',
    description: 'Groceries Nov',
    amount: 2_100_000,
    walletName: 'Cash',
    categoryId: 11,
    excludeFromReport: false,
    category: { id: 11, name: 'Groceries', type: 'outcome', parentId: 10 },
  },
  {
    id: 505,
    date: '2025-11-12',
    description: 'Transport Nov',
    amount: 650_000,
    walletName: 'GoPay',
    categoryId: 20,
    excludeFromReport: false,
    category: { id: 20, name: 'Transport', type: 'outcome', parentId: null },
  },
  {
    id: 506,
    date: '2025-11-15',
    description: 'Savings Nov',
    amount: 3_000_000,
    walletName: 'BCA',
    categoryId: 81,
    excludeFromReport: false,
    category: {
      id: 81,
      name: 'Emergency Savings',
      type: 'outcome',
      parentId: 80,
    },
  },
  {
    id: 507,
    date: '2025-11-20',
    description: 'Education Nov',
    amount: 1_000_000,
    walletName: 'BCA',
    categoryId: 70,
    excludeFromReport: false,
    category: { id: 70, name: 'Education', type: 'outcome', parentId: null },
  },

  // Oct 2025
  {
    id: 601,
    date: '2025-10-01',
    description: 'Salary Oct',
    amount: 12_000_000,
    walletName: 'BCA',
    categoryId: 1,
    excludeFromReport: false,
    category: { id: 1, name: 'Salary', type: 'income', parentId: null },
  },
  {
    id: 602,
    date: '2025-10-05',
    description: 'Freelance Oct',
    amount: 3_000_000,
    walletName: 'Mandiri',
    categoryId: 2,
    excludeFromReport: false,
    category: { id: 2, name: 'Freelance', type: 'income', parentId: null },
  },
  {
    id: 603,
    date: '2025-10-01',
    description: 'Rent Oct',
    amount: 3_500_000,
    walletName: 'BCA',
    categoryId: 31,
    excludeFromReport: false,
    category: { id: 31, name: 'Rent', type: 'outcome', parentId: 30 },
  },
  {
    id: 604,
    date: '2025-10-10',
    description: 'Groceries Oct',
    amount: 1_850_000,
    walletName: 'Cash',
    categoryId: 11,
    excludeFromReport: false,
    category: { id: 11, name: 'Groceries', type: 'outcome', parentId: 10 },
  },
  {
    id: 605,
    date: '2025-10-15',
    description: 'Transport Oct',
    amount: 700_000,
    walletName: 'GoPay',
    categoryId: 20,
    excludeFromReport: false,
    category: { id: 20, name: 'Transport', type: 'outcome', parentId: null },
  },
  {
    id: 606,
    date: '2025-10-15',
    description: 'Savings Oct',
    amount: 3_000_000,
    walletName: 'BCA',
    categoryId: 81,
    excludeFromReport: false,
    category: {
      id: 81,
      name: 'Emergency Savings',
      type: 'outcome',
      parentId: 80,
    },
  },
  {
    id: 607,
    date: '2025-10-20',
    description: 'Shopping Oct',
    amount: 1_100_000,
    walletName: 'BCA',
    categoryId: 51,
    excludeFromReport: false,
    category: { id: 51, name: 'Fashion', type: 'outcome', parentId: 50 },
  },
  {
    id: 608,
    date: '2025-10-22',
    description: 'Health Oct',
    amount: 400_000,
    walletName: 'Cash',
    categoryId: 60,
    excludeFromReport: false,
    category: { id: 60, name: 'Health', type: 'outcome', parentId: null },
  },
];
